# Specify the docker image to use (only used if using docker runners)
# See: http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
image: ubuntu:18.04

variables:
  EXE : "ircserv"

# Define commands that run before each job's script
before_script:
  - apt-get update
  - apt-get install -y xz-utils curl build-essential
  - rm -rf /var/lib/apt/lists/*
  -  curl -SL https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz | tar -xJC .
  - mv clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04 clang_10
  - mv ./clang_10/bin/* /bin/.
  - mv ./clang_10/lib/* /lib/. 

# Try to compile our sample hello world app
compile:
  script:
  # Compile our app
  - make
  # Verify that our compiled executable exists
  - test -f "$EXE"
  # Save the compiled output from the above for downloading via GitLab and in Gitlab 8.6 to use in future steps
  artifacts:
    paths:
    - "$EXE"
